# Generated by Django 4.2.8 on 2026-01-07 19:15

import os
from django.db import migrations


def add_google_oauth_app(apps, schema_editor):
    """Add Google OAuth app configuration from environment variables."""
    Site = apps.get_model('sites', 'Site')
    SocialApp = apps.get_model('socialaccount', 'SocialApp')

    # Get credentials from environment variables
    google_client_id = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')
    google_client_secret = os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', '')

    # Skip if credentials not set
    if not google_client_id or not google_client_secret:
        print("Google OAuth credentials not found in environment, skipping...")
        return

    # Update site domain
    site, _ = Site.objects.get_or_create(id=1, defaults={'domain': 'www.invoicekits.com', 'name': 'InvoiceKits'})
    site.domain = 'www.invoicekits.com'
    site.name = 'InvoiceKits'
    site.save()

    # Create Google OAuth app
    google_app, created = SocialApp.objects.get_or_create(
        provider='google',
        defaults={
            'name': 'Google',
            'client_id': google_client_id,
            'secret': google_client_secret,
        }
    )

    # Update if already exists
    if not created:
        google_app.client_id = google_client_id
        google_app.secret = google_client_secret
        google_app.save()

    # Associate with site
    google_app.sites.add(site)
    print(f"Google OAuth app {'created' if created else 'updated'} successfully!")


def remove_google_oauth_app(apps, schema_editor):
    """Remove Google OAuth app configuration."""
    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    SocialApp.objects.filter(provider='google').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.RunPython(add_google_oauth_app, remove_google_oauth_app),
    ]
