# Generated by Django 4.2.8 on 2026-01-07 19:45

import os
from django.db import migrations


def ensure_social_oauth_apps(apps, schema_editor):
    """Ensure Google and GitHub OAuth apps exist with current env var values."""
    Site = apps.get_model('sites', 'Site')
    SocialApp = apps.get_model('socialaccount', 'SocialApp')

    # Ensure site exists
    site, _ = Site.objects.get_or_create(
        id=1,
        defaults={'domain': 'www.invoicekits.com', 'name': 'InvoiceKits'}
    )
    site.domain = 'www.invoicekits.com'
    site.name = 'InvoiceKits'
    site.save()

    # Google OAuth
    google_client_id = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')
    google_client_secret = os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', '')

    if google_client_id and google_client_secret:
        google_app, created = SocialApp.objects.update_or_create(
            provider='google',
            defaults={
                'name': 'Google',
                'client_id': google_client_id,
                'secret': google_client_secret,
            }
        )
        google_app.sites.add(site)
        print(f"Google OAuth app {'created' if created else 'updated'} successfully!")
    else:
        print("WARNING: Google OAuth credentials not found in environment!")

    # GitHub OAuth
    github_client_id = os.environ.get('GITHUB_OAUTH_CLIENT_ID', '')
    github_client_secret = os.environ.get('GITHUB_OAUTH_CLIENT_SECRET', '')

    if github_client_id and github_client_secret:
        github_app, created = SocialApp.objects.update_or_create(
            provider='github',
            defaults={
                'name': 'GitHub',
                'client_id': github_client_id,
                'secret': github_client_secret,
            }
        )
        github_app.sites.add(site)
        print(f"GitHub OAuth app {'created' if created else 'updated'} successfully!")
    else:
        print("WARNING: GitHub OAuth credentials not found in environment!")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_google_oauth_app'),
        ('sites', '0002_alter_domain_unique'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.RunPython(ensure_social_oauth_apps, migrations.RunPython.noop),
    ]
