# Generated by Django 4.2.8 on 2026-01-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ensure_oauth_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credits_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='free_credits_remaining',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_credits_purchased',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
