# Generated by Django 4.2.8 on 2026-01-09 16:44

from django.db import migrations


def migrate_free_users_to_credits(apps, schema_editor):
    """Give all existing free tier users 5 lifetime credits."""
    CustomUser = apps.get_model('accounts', 'CustomUser')

    # All free users get fresh 5 credits
    # (the default is already 5, but this ensures existing users get updated)
    CustomUser.objects.filter(subscription_tier='free').update(
        free_credits_remaining=5
    )


def reverse_migration(apps, schema_editor):
    """Reverse is a no-op since we're just setting default values."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_credit_system_fields'),
    ]

    operations = [
        migrations.RunPython(
            migrate_free_users_to_credits,
            reverse_migration,
        ),
    ]
