# Generated by Django 4.2.8 on 2026-01-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_migrate_free_users_to_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unlocked_templates',
            field=models.JSONField(blank=True, default=list, help_text='List of premium template slugs unlocked by purchase'),
        ),
    ]
