# Generated by Django 4.2.8 on 2026-03-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_nurture_email_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment_source',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('apple', 'Apple')], default='stripe', help_text='Which payment system manages this user subscription', max_length=10),
        ),
    ]
