# Generated by Django 4.2.8 on 2026-06-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_payment_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('professional', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
