# Generated by Django 4.2.8 on 2026-01-06 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Recommended size: 400x200 pixels', null=True, upload_to='logos/%Y/%m/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('tax_id', models.CharField(blank=True, help_text='EIN, VAT number, etc.', max_length=50)),
                ('default_currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)'), ('INR', 'Indian Rupee (₹)')], default='USD', max_length=3)),
                ('default_payment_terms', models.CharField(choices=[('due_on_receipt', 'Due on Receipt'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60')], default='net_30', max_length=20)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Default tax rate percentage', max_digits=5)),
                ('default_template', models.CharField(default='clean_slate', max_length=50)),
                ('default_notes', models.TextField(blank=True, help_text='Default notes/payment instructions to include on invoices')),
                ('accent_color', models.CharField(default='#3B82F6', help_text='Hex color code for invoice accent color', max_length=7)),
                ('invoice_prefix', models.CharField(default='INV-', help_text='Prefix for invoice numbers', max_length=10)),
                ('next_invoice_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
