# Generated by Django 4.2.8 on 2026-01-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='signature',
            field=models.ImageField(blank=True, help_text='Digital signature image for invoices. Recommended: PNG with transparent background, 400x100 pixels', null=True, upload_to='signatures/%Y/%m/'),
        ),
    ]
