# Generated by Django 4.2.8 on 2026-01-14 17:32

from django.db import migrations


def populate_owner_from_user(apps, schema_editor):
    """Copy the user field to owner field for all existing companies."""
    Company = apps.get_model('companies', 'Company')
    for company in Company.objects.filter(owner__isnull=True, user__isnull=False):
        company.owner = company.user
        company.save(update_fields=['owner'])


def reverse_populate_owner(apps, schema_editor):
    """Reverse migration - no action needed as owner will be dropped."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_add_team_seats'),
    ]

    operations = [
        migrations.RunPython(
            populate_owner_from_user,
            reverse_populate_owner
        ),
    ]
