# Generated by Django 4.2.8 on 2026-01-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_populate_owner_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect account ID for receiving payments', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_connect_charges_enabled',
            field=models.BooleanField(default=False, help_text='Whether the account can accept charges'),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_connect_connected_at',
            field=models.DateTimeField(blank=True, help_text='When Stripe Connect was connected', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_connect_onboarding_complete',
            field=models.BooleanField(default=False, help_text='Whether Stripe Connect onboarding is complete'),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_connect_payouts_enabled',
            field=models.BooleanField(default=False, help_text='Whether the account can receive payouts'),
        ),
    ]
