# Generated by Django 4.2.8 on 2026-01-07 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('invoices', '0002_invoice_invoice_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name (e.g., "Monthly Retainer - Acme Corp")', max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=50)),
                ('client_address', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for indefinite recurring', null=True)),
                ('next_run_date', models.DateField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)'), ('INR', 'Indian Rupee (₹)')], default='USD', max_length=3)),
                ('payment_terms', models.CharField(choices=[('due_on_receipt', 'Due on Receipt'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60')], default='net_30', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('template_style', models.CharField(default='clean_slate', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('invoices_generated', models.PositiveIntegerField(default=0)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('send_email_on_generation', models.BooleanField(default=True, help_text='Email owner when invoice is generated')),
                ('auto_send_to_client', models.BooleanField(default=False, help_text='Automatically send invoice to client email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_invoices', to='companies.company')),
                ('last_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_source', to='invoices.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('recurring_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.recurringinvoice')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='recurringinvoice',
            index=models.Index(fields=['company', 'status'], name='invoices_re_company_1f747e_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringinvoice',
            index=models.Index(fields=['next_run_date', 'status'], name='invoices_re_next_ru_e24d12_idx'),
        ),
    ]
