# Generated by Django 4.2.8 on 2026-01-14 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_recurringinvoice_recurringlineitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for public invoice access', unique=True),
        ),
    ]
