# Generated by Django 4.2.8 on 2026-01-16 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_stripe_connect_account_id_and_more'),
        ('invoices', '0004_add_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reminders_paused',
            field=models.BooleanField(default=False, help_text='Pause automated payment reminders for this invoice'),
        ),
        migrations.CreateModel(
            name='PaymentReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminders_enabled', models.BooleanField(default=False, help_text='Enable automated payment reminders')),
                ('remind_3_days_before', models.BooleanField(default=True)),
                ('remind_1_day_before', models.BooleanField(default=True)),
                ('remind_on_due_date', models.BooleanField(default=True)),
                ('remind_3_days_after', models.BooleanField(default=True)),
                ('remind_7_days_after', models.BooleanField(default=True)),
                ('remind_14_days_after', models.BooleanField(default=True)),
                ('cc_business_owner', models.BooleanField(default=False, help_text='Send a copy of reminders to business owner')),
                ('custom_message_before', models.TextField(blank=True, help_text='Custom message for reminders before due date')),
                ('custom_message_due', models.TextField(blank=True, help_text='Custom message for reminder on due date')),
                ('custom_message_overdue', models.TextField(blank=True, help_text='Custom message for reminders after due date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to='companies.company')),
            ],
            options={
                'verbose_name': 'Payment Reminder Settings',
                'verbose_name_plural': 'Payment Reminder Settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_offset', models.IntegerField(help_text='Days relative to due date (negative=before, 0=on due, positive=after)')),
                ('reminder_type', models.CharField(choices=[('before', 'Before Due Date'), ('due', 'On Due Date'), ('overdue', 'Overdue')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Payment Reminder Log',
                'verbose_name_plural': 'Payment Reminder Logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['invoice', 'days_offset'], name='invoices_pa_invoice_57b5b7_idx')],
                'unique_together': {('invoice', 'days_offset')},
            },
        ),
    ]
