# Generated by Django 4.2.8 on 2026-01-17 01:20

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0006_add_late_fee_settings'),
        ('invoices', '0007_add_late_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTrackingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Default hourly rate for new time entries', max_digits=10)),
                ('rounding_increment', models.PositiveIntegerField(choices=[(1, '1 minute'), (5, '5 minutes'), (6, '6 minutes (0.1 hour)'), (15, '15 minutes'), (30, '30 minutes')], default=1, help_text='Round time entries to nearest increment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_tracking_settings', to='companies.company')),
            ],
            options={
                'verbose_name': 'Time Tracking Settings',
                'verbose_name_plural': 'Time Tracking Settings',
            },
        ),
        migrations.CreateModel(
            name='ActiveTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='What are you working on?', max_length=500)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate for this timer session', max_digits=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_timers', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_timers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Active Timer',
                'verbose_name_plural': 'Active Timers',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('client_email', models.EmailField(blank=True, help_text='Client email for grouping time entries', max_length=254)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate for this entry', max_digits=10)),
                ('billable', models.BooleanField(default=True, help_text='Whether this time is billable')),
                ('status', models.CharField(choices=[('unbilled', 'Unbilled'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='unbilled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='companies.company')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='invoices.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Entry',
                'verbose_name_plural': 'Time Entries',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='invoices_ti_company_169028_idx'), models.Index(fields=['company', 'date'], name='invoices_ti_company_d0399b_idx'), models.Index(fields=['user', 'date'], name='invoices_ti_user_id_e342dd_idx'), models.Index(fields=['client_email'], name='invoices_ti_client__8b9fd4_idx')],
            },
        ),
    ]
