# Generated by Django 4.2.8 on 2026-09-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_guest_voice_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_reported_at',
            field=models.DateTimeField(blank=True, help_text='When the client last said, from the public link, that they had paid', null=True),
        ),
    ]
